### ISSUE TITLE
error "binary operator expected"

### ISSUE THREAD

**Issue by dprotti** [MatiMoreyra/icecc-available-jobs#4]
If I run on host 192.168.0.42 I get this output:
`$ icecc-jobs.sh`
`~/.local/bin/icecc-jobs.sh: line 48: test: 192.168.0.42: binary operator expected`
`nc: port number invalid: 192.168.0.104`
`Ups! The scheduler is not responding.`

The scheduler is in fact running in 192.168.0.104 and is reachable from 192.168.0.42.

**Comment by MatiMoreyra** [comment]
Thanks for reporting! The script assumes that no other machine in the network has the port 8766 open.

Could you please verify that? Use:
```
nmap --open -Pn 192.168.0.* -p 8766
```

As a workaround, you can use:
```
icecc-jobs.sh -s 192.168.0.104
```

**Comment by dprotti** [comment]
Yes indeed, by mistake both machines were running icecc-scheduler.

Could the script detect this and display a message accordingly?

Wouldn't be a bug but rather an enhancement.

**Comment by MatiMoreyra** [comment]
Sure, created issue #5. Thank you very much for this suggestion!
